### ISSUE TITLE
Lesson for routing - Questions 

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/RoutingBundle#262]
Hey,

would need some clearing work in my head for the routing and the values i can set when using the admin (with sonata admin) for the routes. I have got an example to show my problem.

On the one hand i have got routes of some documents that i created while creation of the documents. Those got a little prefix for the domain they belong to, like a bicycle tour route is persisted in:
```
/cms/routes/www.my-domain.de/tours/example-tour
```
I have got a route provide and a filter to get the matches depending on the current host/domain. That works fine and is cool. But now i wanna have routes with parameters and match a `controller:action` and wanna provide one of that parameter routes in the menu. So i thought i need to create a route like: 
``` 
/cms/routes/www.my-domain.de/service/{service-name}
``` 
means a route with a localname `service` and an parameter `severice-name` But when navigating to that route i got an 404. The thing i wanna have is: 
```
bobb_projectx_tour.themes:
    defaults: { _controller: bobb_projectx_tour.controller.tour_content:themesAction, tourName: neckartal-radweg }
    path: /informationen/themenbereiche/{tourName}
```
here i create a simple symfony route with the same behavior, cause i did not get it with the cmf routing.
Is it possible that i destroy some stuff of the route matching, caused by my own route provider?
Is there an easier way then with the route provider? Haven't found a doc about that candidate stuff. 

And what would be the part (when it work) to put into the menu route field? I thought the route name is that part, which the route is able convert into a route object with an matching content document, right? So i would need to insert `/www.my-domain.de/servcice/e-bike-station` (special service) into my route field of the menu entry?

**Comment by dbu** [comment]
@ElectricMaxxx can we close this one or do we need to still do something about this?

**Comment by ElectricMaxxx** [comment]
Close.
