### ISSUE TITLE
Is there a way to expose the routes with FOSJsRoutingBundle?

### ISSUE THREAD

**Issue by idhard** [symfony-cmf/RoutingBundle#283]
Hello,
I would like to know if is possible to expose the page_slug route with the bundle FOSJsRoutingBundle,

Could we use the routing system in the client side like this ?:

 Routing.generate('page_slug',{path: '/about-us'});

thanks in advance.

**Comment by dbu** [comment]
yes, that is possible. however, the "name" of the routes are the repository paths. so you would need to configure the repository path as route to expose in js routingbundle. or you can configure whole name patterns for routes i think.

**Comment by dbu** [comment]
look at the output of app/console router:debug in the sandbox to see what routes are exposed.

**Comment by idhard** [comment]
@dbu  Thanks for you quick answer, im not working with cmf at the moment i have an implementation of Sonata integrating the routing bundle , i will install the sandbox and give a try this WE. You could label the issue as a question, probably for others would be usefull.

**Comment by dbu** [comment]
this is documented here: http://symfony.com/doc/current/cmf/bundles/routing/dynamic.html#url-generation-with-the-dynamicrouter - we keep the issue tracker for unresolved issues, so i will close this issue. but don't hesitate to open new issues if you have further questions.
