### ISSUE TITLE
LastModifiedDate and  CreatedDate for routes

### ISSUE THREAD

**Issue by joiz** [symfony-cmf/RoutingBundle#289]
Is there a reason why routes have no LastModifiedDate and  CreatedDate like any other cmf document?
This would be very helpful in the admin.
If it makes sense we will add it .
Cheers
Eric

**Comment by lsmith77** [comment]
we just didn't think its used in most cases. of course it can be added by extending the base class.

**Comment by dbu** [comment]
+1 on extending the provided routing document if you need this feature.

**Comment by joiz** [comment]
ok

**Comment by dbu** [comment]
@joiz note that with the phpcr-shell, it should be very easy to do an SQL2-style update statement to change the document class of all your route documents.

**Comment by joiz** [comment]
thanks for the hint @dbu  - we used php code for this in the past - but i will look into the phpcr-shell

**Comment by dantleech** [comment]
note that the current beta has some issues, but plan to release beta-2 today :) Updating is pretty easy: http://phpcr.readthedocs.org/en/latest/phpcr-shell/querying.html#update-and-delete
