### ISSUE TITLE
Package sonata-project/jquery-bundle is abandoned

### ISSUE THREAD

**Issue by pbeliberty** [symfony-cmf/RoutingBundle#294]
RoutingBundle 
requires 
sonata-project/doctrine-phpcr-admin-bundle: ~1.1

sonata-project/admin-bundle: >=2.2.9,<=2.2.12 
requires 
sonata-project/jquery-bundle: 1.8.*

But sonata-project/jquery-bundle: is abandoned

And cause a critical error....

I saw that sonata and doctrine-phpcr-admin-bundle have new version which work without jQueryBundle...

**Comment by dbu** [comment]
yep, the next version of sonata will get us rid of this. but anyways, the sonata admin is only needed as require-dev in the routing bundle, so you should only see this when developing on the RoutingBundle, or when requiring sonata admin separately.
