### ISSUE TITLE
Problems with composer install

### ISSUE THREAD

**Issue by henrypenny** [symfony-cmf/RoutingBundle#307]
I'm currently having issues installing this bundle with composer.
The Symfony bootstrap seems to be looking for the bundle here:

`./vendor/symfony-cmf/routing-bundle/Symfony/Cmf/Bundle/RoutingBundle/CmfRoutingBundle.php`

Whereas the bundle class is here:

`./vendor/symfony-cmf/routing-bundle/CmfRoutingBundle.php`

I'm using v 1.3.5

**Comment by henrypenny** [comment]
I've resolved this issue. But I have no idea why it happened. I don't think its a problem with this bundle since I found it had affected other bundles - so I'm going to close it.

**Comment by dbu** [comment]
this looks like psr4 vs psr0 path. did you upgrade from and old version
recently, maybe?

**Comment by henrypenny** [comment]
There was a `"post-root-package-install"` in `"scripts"` in my `composer.json` and the script it pointed to was no longer present. I removed that and everything started to work. I don't think composer install was completing properly - although there was no error.
I really doubt its a problem with this Bundle - more likely a catastrophic skills failure on my part!

**Comment by henrypenny** [comment]
But yes, it did look like that.

**Comment by dbu** [comment]
ah, so the autoloading map was never updated... yeah then makes sense.
