### ISSUE TITLE
SchemaException when using symfony 2.7 and persistence.orm.enabled:tue

### ISSUE THREAD

**Issue by Nielsb85** [symfony-cmf/RoutingBundle#309]
after composer require symfony-cmf/routing-bundle

config.yml:

```
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default:             100
    dynamic:
            persistence:
                orm:
                    enabled:      true
                  
```

and register in AppKernel.php

on command line
```
php app/console doctrine:schema:update --dump-sql
```

will throw an Exception in symfony 2.7 with orm

```
Doctrine\DBAL\Schema\SchemaException]                              
  There is no column with name 'staticPrefix' on table 'orm_routes'.  
                                                                    
```

the table is not even created yet.

When creating a new symfony demo project (which uses sqlite) it works fine.
But not with pdo_mysql

**Comment by dbu** [comment]
this looks really strange. are you using orm 2.5 or 2.4? can you try with the other version? it sounds a lot like 

we build this bundle on travis and while there are not many tests on the orm entity, we do generate the schema and it works - but we use sqlite there.

@edgartebar contributed a fix for mysql very recently because one column was using a mysql reserved keyword. @edgartebar would you have any input on this?

**Comment by Nielsb85** [comment]
We use the symfony installer. start with a clear install and getting the routerbundle vendor first.
We use orm 2.4. I just tried 2.5 but there is no difference.

```

       
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "symfony-cmf/routing-bundle": "^1.3",
  
  
```

We did not have any problem with sqlite either. But in this case we need mysql

**Comment by dbu** [comment]
hm. i really don't know then. if @edgartebar has no idea, i fear you would have to dig into this. try to look at the mapping and see if you can remove things until it works, to identify what makes things fail. but at this point it sounds to me like something with doctrine + mysql got very confused.

**Comment by Nielsb85** [comment]
in routing-bundle/Resources/config/doctrine-model/Route.orm.xml


```
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://raw.github.com/doctrine/doctrine2/master/doctrine-mapping.xsd">

    <mapped-superclass name="Symfony\Cmf\Bundle\RoutingBundle\Model\Route">
        <field name="variablePattern" type="string" nullable="true"/>
        <field name="staticPrefix" type="string" nullable="true"/>

        <indexes>
            <index name="name_idx" columns="name"/>
            <index name="prefix_idx" columns="staticPrefix"/>
        </indexes>
    </mapped-superclass>

</doctrine-mapping>
```

where``` <index name="prefix_idx" columns="staticPrefix"/> ``` does not work in the default installation of symfony 2.7 because of config.yml:

```
  orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```

With that setting the column names are not camel cased but use underscore (static_prefix) 

We could either rename ```<index name="prefix_idx" columns="staticPrefix"/>``` to ```<index name="prefix_idx" columns="static_prefix"/> ```

but its cleaner for now to remove the default naming_strategy setting in config.yml .

**Comment by dbu** [comment]
ah, this is not elegant. could we define the index on the field instead of the column name? it looks like a breach of abstraction. otherwise we would need to explicitly specify the column name in the mapping, if we need to specify the column in the index. changing the column to underscore now would be a BC break for existing systems.

@Nielsb85 can you check on this and do a PR to either fix the index to be flexible or make the field mapping explicit to match what we say in index?

**Comment by steve-todorov** [comment]
I can confirm what @Nielsb85 says. I'm ran into this problem while building a bundle which depends on Symfony CMF `RoutingBundle`. I, as well, had the default Symfony configuration which had `naming_strategy` in the `config.yml` and that lead to the same exception. Commenting out the `naming_strategy` seems to be solving the problem for now.

**Comment by dbu** [comment]
thanks. i am not too familiar with the details, if one of you can provide a pull request to make this more robust, i would greatly appreciate it.

**Comment by Nielsb85** [comment]
I was not able to find a way to add the index on the field name. For us, removing the naming_strategy works for now.

**Comment by edgartebar** [comment]
I'm sorry but i didn't see this before, i am very busy this week XD,  this evening i will take a look @dbu

**Comment by dbu** [comment]
ping

**Comment by lsmith77** [comment]
@Ocramius maybe I bother you once again with a Doctrine issue .. do you have a hint for us how we can do indexes in our default configs that do not conflict with naming strategies?

**Comment by dbu** [comment]
i think #330 should solve this. i simply hardcode the column name so we don't use the naming strategy for those fields. but if @Ocramius has a more elegant idea, i am all open for it. reading the xml mapper, it looks like you can only specify a column on an index definition, not a field name. hence the column name must be known..

**Comment by Ocramius** [comment]
@lsmith77 sorry, not sure how you could avoid conflicts besides prefixing
