### ISSUE TITLE
support for repository enhancer

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/RoutingBundle#337]
in #168 we added a content repository enhancer. this enhancer should also be useable in the bundle.

/cc @andrey1s

**Comment by andrey1s** [comment]
@dbu add enhancer only ORM or if exist content repository?

**Comment by dbu** [comment]
good question. looking at the other enhancers, the content repository check should be used. somebody might also use PHPCR routes and a content repository with something else (elasticsearch, mongodb, whatever). as soon as a content repository exists, the enhancer is potentially useful.

**Comment by dbu** [comment]
#338 has been merged.

**Comment by dbu** [comment]
please also update the minimum requirement of symfony-cmf/routing to ^1.4.0 so that we get the right version.
